theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

repository: yxwzaxns/uni-utils
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
