plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: yxwzaxns/just-the-docs

repository: yxwzaxns/uni-utils
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
